.PHONY: all clean

CC_OPTS		= -DOGS_SDL2
CFLAGS		= $(CC_OPTS) `sdl2-config --cflags`
CXXFLAGS	= $(CFLAGS)

TARGET=sokoban
SRC=sokoban.cpp Functions.cpp CUsbJoystickSetup.cpp CInput.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	g++ $(CXXFLAGS) $(SRC) -o $@ -lSDL2  -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lSDL2_gfx

clean:
	rm -rf $(TARGET)

